---
title: "Specifying Fixed Parameters"
author: "John C. Nash"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Motivation

In finding optimal parameters in nonlinear optimization and nonlinear 
least squares problems, we frequently wish to fix one or more parameters
while allowing the rest to be adjusted to explore or optimize an objective 
function. 

This vignette discusses some ideas about specifying the fixed parameters. A 
lot of the material is drawn from Nash J C (2014) **Nonlinear parameter 
optimization using R tools** Chichester UK: Wiley, in particular chapters
11 and 12.


# Background

Here are some of the ways fixed parameters may be specified in R packages.

From `nlsrxb`

masked  

Character vector of quoted parameter names. These parameters will NOT be altered by the algorithm.

From `nlsrfb`

maskidx  

?? This needs to be changed to use names!?? Vector if indices of the parameters to be masked. 
These parameters will NOT be altered by the algorithm. Note that the mechanism here is different 
from that in nlxb which uses the names of the parameters.

